print ('vamos a jugar')
print ('Te pido que completes las operaciones y yo adivino el numero que pensaste')
input('Presiona enter cuando finalices')
print ('Piensa en un numero')
input('Presiona enter cuando estes listo')
print('Multiplica ese numero por 2')
input('Presiona enter cuando estes listo')
print('Sumale 10 a ese valor')
input('Presiona enter cuando estes listo')
print ('Dividelo por 2')
input('Presiona enter cuando estes listo')
print('Restale tu numero inicial')
input('Presiona enter cuando estes listo')
input('el numero quen tienes en mente es...')
input('5')

